AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Deutzia:  CFN Template To CloudTrail Trail for Data Event.

Metadata:
  TemplateName: cloudtrail-stack.yaml
  TemplateType: CloudTrail Trail
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Deutzia
  Modification History:
    - 1.0.0   - June 29, 2023           -- Initial Version 
  Resources: 
    - CloudTrail Trail
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    # - Label: 
    #     default: "KMS Configuration:"
    #   Parameters: 
    #   - KmsMasterKeyAlias
    #################################### CloudTrail ################################################
    - Label: 
        default: "CloudTrail Configuration:"
      Parameters:
        - CloudTrailBaseName
        - CloudWatchLogGroupBaseName
        - S3BucketBaseName
        - S3DefaultFolder
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBTableBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "The Project Name."
      Environment:
        default: "Environment Name."
      ################################## KMS #######################################################
      # KmsMasterKeyAlias: 
      #   default: "The KMS Master Key Alias To Be Used For Server Side Encryption."
      ################################## SNS #######################################################
      ################################## CloudTrail ################################################
      CloudWatchLogGroupBaseName:
        default: "The Base Name The CloudWatch Log Group.The Region And Environment Will Be Added As Suffix By The Template."
      CloudTrailBaseName:
        default: "The Base Name of the CloudTrail Trail."
      S3BucketBaseName:
        default: "CloudTrail S3 Bucket."
      S3DefaultFolder:
        default: "Default folder of CloudTrail trail."
      ################################## DynamoDB Table ############################################
      DynamoDBTableBaseName: 
        default: "DynamoDB Table."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  # KmsMasterKeyAlias:
  #   Default: "SB-KMS"
  #   Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
  #   Type: String
  #   MinLength: 5
  #   MaxLength: 20
  #   AllowedPattern: "[a-zA-Z0-9-]*"
  #   ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ###################################### S3 Bucket #################################################
  S3BucketBaseName:
    Default: cloudtrail
    Description: "The S3 Bucket Base Name For The CloudTrail Data. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  S3DefaultFolder:
    Default: "cloud-trail"
    Description: "The Folder To Be Created For Storing The Raw Data. Use Do_not_create If You Do Not Want To Create Any Folder."
    Type: String
    ConstraintDescription: "Should be a comma seperated folder names." 
  ###################################### CloudWatch ################################################
  CloudWatchLogGroupBaseName:
    Default: cloudtrail-logs
    Description: "The Base Name The CloudWatch Log Group.The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
  ###################################### CloudTrail ################################################
  CloudTrailCloudWatchRoleName:
    Default: cloudtrail-iam-role
    Description: "The Execution Role Of The CloudTrail CloudWatch Log."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: "Must be between 5 and 255 characters long and begin with a letter and can contain number or hyphen (-)."
  CloudTrailBaseName:
    Default: scan-cw-logs
    Description: "The Base Name The Lambda Function. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
  ###################################### DynamoDB Table ############################################
  DynamoDBTableBaseName:
    Default: products
    Description: "The Name Of The Dynamodb Table."
    Type: String
    MinLength: 8
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
Resources:
  ###################################### CloudTrail Trail ##########################################
  CloudTrailTrail:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName:  !Sub "${ProjectName}-${S3BucketBaseName}-${Environment}-${AWS::Region}"
      S3KeyPrefix: !Ref S3DefaultFolder
      IsLogging: true
      TrailName: !Sub '${ProjectName}-${CloudTrailBaseName}-${Environment}-${AWS::Region}'
      EnableLogFileValidation: false
      IncludeGlobalServiceEvents: false
      IsMultiRegionTrail: false
      CloudWatchLogsLogGroupArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ProjectName}-${CloudWatchLogGroupBaseName}-${Environment}-${AWS::Region}:*'
      CloudWatchLogsRoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ProjectName}-${CloudTrailCloudWatchRoleName}'
      # KMSKeyId: !Sub 'alias/${KmsMasterKeyAlias}
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key:  Environment
        Value: !Ref Environment
      # SnsTopicName:
      #   Fn::ImportValue: TrailTopicTest
      EventSelectors:
        - DataResources:
            - Type: AWS::DynamoDB::Table
              Values: 
                - !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-${DynamoDBTableBaseName}-${Environment}-${AWS::Region}'
          IncludeManagementEvents: false
          ReadWriteType: All
Outputs:
  CloudTrailArn:
    Description: The URL of the CloudTrail Trail with Data Event.
    Value: !GetAtt CloudTrailTrail.Arn
